/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

fun add(num1:Double,num2:Double):Double{
    return num1+num2
}


fun main(){
    val num1=10.0
    val num2=5.0
val result=add(num1,num2)
println("$num1 +$num2= $result")
}
